config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"
  get 'pages/home', to: 'pages#home'
  
  resources :recipes do
    member do
      put "like", to: "recipes#upvote"
      put "dislike", to: "recipes#downvote"
    end
    resources :comments, only: [:create]
  end
  
  resources :ingredients, except: [:destroy]
  
  get "/signup", to: 'chefs#new'
  resources :chefs, except: [:new]
  
  get "/login", to: 'sessions#new'
  post "/login", to: 'sessions#create'
  delete "/logout", to: 'sessions#destroy'
  
  mount ActionCable.server => '/cable'
  
  get '/chat', to: 'chatrooms#show'
  
  resources :messages, only: [:create]
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true, length: {minimum: 5, maximum: 500}
  validates :chef_id, presence: true
  
  
    
  belongs_to :chef
  acts_as_votable
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :comments, dependent: :destroy
  default_scope -> { order(updated_at: :desc) }
  
  mount_uploader :image, ImageUploader
  
 
end 

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:edit, :show, :update, :destroy, :upvote, :downvote]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 5)
  end
  
  def show
    @comment = Comment.new
    @comments = @recipe.comments.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = current_chef
    
    if @recipe.save
      flash[:notice] = "Recipe was successfully created"
      redirect_to recipe_path(@recipe)
    else
      render 'new'
    end
  end  
  
  def edit
    
  end
  
  def update
    if @recipe.update(recipe_params)
      flash[:notice] = "Recipe was successfully updated"
      redirect_to recipe_path(@recipe)
    else
      render 'edit'
    end 
  end
  
  def destroy
    @recipe.destroy
      flash[:notice] = "Recipe was successfully deleted." 
      redirect_to recipes_path
  end
  
  def upvote
    @recipe.upvote_by current_chef
    flash[:success] = "Successfully liked"
    respond_to do |format|
      format.html {redirect_to recipes_path }
      format.json { render json: { count: @recipe.liked_count } }
    end
  end
  
  def downvote
    @recipe.downvote_by current_chef
    flash[:success] = "Successfully disliked"
    respond_to do |format|
      format.html {redirect_to recipes_path }
      format.json { render json: { count: @recipe.disliked_count } }
    end
  end
  
  private
    
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end
  
    def recipe_params
      params.require(:recipe).permit(:name, :description, :image, ingredient_ids: [])
    end
    
    def require_same_user
      if current_chef != @recipe.chef and !current_chef.admin?
        flash[:danger] = "You can only edit or delete your own recipes"
        redirect_to recipes_path
      end
    end

end

app/views/recipes/_form.html.erb
<%= render "shared/errors", obj: @recipe %>
 
<div class="col-md-12">
  <%= form_for(@recipe, :html => {multipart: true, class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-md-2"><%= f.label :name %></div>
      <div class="col-md-8" ><%= f.text_field :name, class: "form-control", placeholder: "Name of recipe", autofocus: true %></div>
    </div>
    <div class="form-group">
      <div class="control-label col-md-2"><%= f.label :description %></div>
      <div class="col-md-8" ><%= f.text_area :description, class: "form-control", rows: 10, placeholder: "Enter steps for recipe" %></div>
    </div>
    <div class="form-group">
      <div class="control-label col-md-2"><%= f.label :image, "Add Image" %></div>
      <div class="col-md-8"><%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %></div>
    </div>
    
    <div class="form-group">
      <div class="col-md-offset-2 col-md-8">
        <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cb| %>
          <% cb.label(class: "checkbox-inline input-checkbox") { cb.check_box(class: "checkbox") + cb.text } %>
        <% end %>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-md-offset-2 col-md-8 back-link"><%= f.submit class:"btn btn-default btn-xl"%></div> 
    </div>
  <% end %>
  
</div>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
    <div class="row">
      <div class="col-md-2">
        <section class="center">
          <%= link_to gravatar_for(recipe.chef, size: 120), recipes_path %>
        </section>
      </div>
      <div class="col-md-8 well">
        <h3><%= link_to recipe.name, recipe_path(recipe) %></h3>
        <p><%= truncate(recipe.description, length: 150) %></p>
        <%  if recipe.ingredients.any? %>
          <p>Ingredients: <%= render recipe.ingredients %></p>
        <% end %>
        
        <%= link_to like_recipe_path(recipe), method: :put do %>
          <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"> Likes:</span>
            <%= recipe.get_upvotes.size %>
        <% end %>
        &nbsp;
        <%= link_to dislike_recipe_path(recipe), method: :put do %>
          <span class="glyphicon glyphicon-thumbs-down " aria-hidden="true"> Dislikes:</span>
            <%= recipe.get_downvotes.size %>
        <% end %>
        <br />
        <br />
        
        <p>
          <span class="quiet"></span><small>Created <%= time_ago_in_words(recipe.created_at) %> ago by <%= recipe.chef.chefname.capitalize %>
                                                        | <%= pluralize(recipe.comments.count, "Comment")  %></small></span>
        </p>
        
        
        <% if logged_in? && (current_chef == recipe.chef || current_chef.admin?) %>
        <div class="recipe-actions">
          <%= link_to '[ edit this recipe ]', edit_recipe_path(recipe), class: "btn btn-warning" %>
          <%= link_to 'delete this recipe', recipe_path(recipe), method: :delete,
                  data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </div>
        <% end %>
      </div>
      <div class="col-md-2">
        <%= image_tag(recipe.image.url, size: "150 X 100", class: "recipe-image") if recipe.image? %>
      </div>
    </div>
  <% end %>

app/views/recipes/edit.html.erb
<div class="container">

  <%= render "shared/page_title", title: "edit recipe" %>
  
  <%= render 'form' %>
  
  <div class="col-md-offset-4 col-md-4 back-link"><%= link_to '[ cancel and go back to listing ]', recipes_path %></div> 

app/views/recipes/index.html.erb
<div class="container">

  <%= render "shared/page_title", title: "listing of recipes" %>
  
  <div align="center">
    <%= will_paginate %>
  </div>
  
  <%= render 'recipe', obj: @recipes %>
  
  <div align="center">
    <%= will_paginate %>
  </div>

app/views/recipes/new.html.erb
<div class="container">

<%= render "shared/page_title", title: "submit a new recipe" %>

<%= render 'form' %>
  
<div class="col-md-offset-4 col-md-4 back-link"><%= link_to '[ cancel and go back to listing ]', recipes_path %></div> 
    
  

app/views/recipes/show.html.erb
<div class="container">

  <%= render "shared/page_title", title: @recipe.name %>
  
  <div class="well col-md-8 col-md-offset-2">
    <div class="center"><%= image_tag @recipe.image.url if @recipe.image? %></div> 
    <hr>
    <h4 class="center description"><strong>Steps: </strong></h4> 
    <hr>
    
    <div><%= simple_format(@recipe.description) %></div>
    <hr>
    
    <% if @recipe.ingredients.any? %>
      <p>Ingredients: <%= render @recipe.ingredients %></p>
    <% end %>
    
    <div class="pull-right">
      <p class="center">
        <em>Created by:</em> 
      </p>
      <p class="center">
        <%= link_to gravatar_for(@recipe.chef), chef_path(@recipe.chef) %>
      </p>
      <p class="center">
        <small><%= @recipe.chef.chefname.capitalize %></small>
        <div class="pull-right">created: <%= time_ago_in_words(@recipe.created_at) %> ago</div>
      </p>
    </div>
    
    <div class="recipe-actions">
      <%= link_to like_recipe_path(@recipe), method: :put do %>
        <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"> Likes:</span>
          <%= @recipe.get_upvotes.size %>
      <% end %> 
      &nbsp;
      <%= link_to dislike_recipe_path(@recipe), method: :put do %>
        <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"> Dislikes:</span>
          <%= @recipe.get_downvotes.size %>
      <% end %>
      <br />
      <br />
      
      <% if logged_in? && (current_chef == @recipe.chef || current_chef.admin?) %>
        <%= link_to '[ edit this recipe ]', edit_recipe_path, class: "btn btn-warning" %>
        <%= link_to 'delete this recipe', recipe_path(@recipe), method: :delete,
                  data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      <% end %>
    </div>
    
  </div>
  
  <% if logged_in? %>
    
      <div class="col-md-8 col-md-offset-2">
        <h3>Comment: </h2>
        <hr>
        <%= form_for [@recipe, @comment], remote: true do |f| %>
          <div class="form-group">
            <div class="control-label col-md-2"><%= f.label :comment %></div>
            <div class="col-md-10" ><%= f.text_area :description, class: "form-control", rows: 3, placeholder: "Enter comment" %></div>
          </div>
          <div class="form-group">
            <div class="col-md-offset-2 col-md-8 back-link"><%= f.submit "submit comment", class:"btn btn-default btn-xl" %></div> 
          </div>
        <%  end %>
      </div>
   
  <% end %>
  
  <% if @recipe.comments.any? %>
    <div class="col-md-8 col-md-offset-2">
      <h3>Prior Comments: </h3>
      <div id="comments">
        <div id="messages">
          <%= render partial: 'comments/comments', object: @comments %>
        </div>
      </div>
    </div>
  <% else %>
    <div class="col-md-8 col-md-offset-2">
      <h3>No Comments Yet!</h3>
    </div>
  <% end %>
  
  