config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"
  get 'pages/home', to: 'pages#home'
  
  resources :recipes do
    member do
      put "like", to: "recipes#upvote"
      put "dislike", to: "recipes#downvote"
    end
    resources :comments, only: [:create]
  end
  
  resources :ingredients, except: [:destroy]
  
  get "/signup", to: 'chefs#new'
  resources :chefs, except: [:new]
  
  get "/login", to: 'sessions#new'
  post "/login", to: 'sessions#create'
  delete "/logout", to: 'sessions#destroy'
  
  mount ActionCable.server => '/cable'
  
  get '/chat', to: 'chatrooms#show'
  
  resources :messages, only: [:create]
  
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximim: 25 }
  validates_uniqueness_of :name
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update]
  before_action :require_admin, except: [:index, :show]
  
  def index
    @ingredients = Ingredient.paginate(page: params[:page], per_page: 5) 
  end
  
  def new
    @ingredient = Ingredient.new
  end
  
  def show
    @ingredient_recipes = @ingredient.recipes.paginate(page: params[:page], per_page: 5)
  end
  
  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      flash[:success] = "Ingredient was successfully added"
      redirect_to ingredient_path(@ingredient)
    else
      render 'new'
    end
  end

  def edit
    
  end
  
  def update
    if @ingredient.update(ingredient_params)
      flash[:notice] = "Ingredient name was successfully updated"
      redirect_to @ingredient
    else
      render 'edit'
    end 
  end
  
  private 
  
  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end
  
  def ingredient_params
    params.require(:ingredient).permit(:name)
  end
  
  def require_admin
    if !logged_in? || (logged_in? && !current_chef.admin?)
      flash[:danger] = "Only admin users can perform that action"
      redirect_to ingredients_path
    end
  end
  
end
  

app/views/ingredients/_form.html.erb
<%= render "shared/errors", obj: @ingredient %>

<div class="col-md-12 signup-form">
  <%= form_for(@ingredient, :html => {class: "form-horizaontal", role: "form"}) do |f| %>
    <div class="form-group">
      <%= f.label :name, "Name" %>
      <%= f.text_field :name, class: "form-control", placeholder: "enter ingredient ame", autofocus: true %>
    </div>
    <div class="form-group">
      <div><%= f.submit(@ingredient.new_record? ? "Add ingredient" : "Update ingredient", class:"btn btn-default btn-xl") %></div> 
    </div>
  <% end %>
</div>

<div class="col-md-offset-4 col-md-4 back-link"><%= link_to '[ cancel and go back to ingredients listing ]', ingredients_path %></div> 

app/views/ingredients/_ingredient.html.erb
<span class="badge"><%= link_to ingredient.name, ingredient_path(ingredient) %></span>

app/views/ingredients/edit.html.erb
<div class="container">
  
  <%= render "shared/page_title", title: "edit ingredient name" %>
  
  <%= render 'form' %>

app/views/ingredients/index.html.erb
<div class="container">

  <%= render "shared/page_title", title: "available ingredients" %>
  
  <div align="center">
    <%= will_paginate %>
    <% @ingredients.each do |ingred| %>
      <ul class="listing">
        <div class="row">
          <div class=" well col-md-4 col-md-offset-4">
            
            <li class="chef-title"><%= link_to ingred.name.capitalize, ingredient_path(ingred) %></li>
            
            <li><small><%= pluralize(ingred.recipes.count, "recipe") if ingred.recipes %></small></li>
            <% if logged_in? && current_chef.admin?  %>
              <li><%= link_to "edit this ingredient", edit_ingredient_path(ingred), class: "btn btn-danger"%></li>
            <% end %>
          </div>
        </div>
      </ul>
    <% end %>
    <%= will_paginate %>
  </div>

app/views/ingredients/new.html.erb
<div class="container">
  
  <%= render "shared/page_title", title: "add new ingredient" %>
  
  <%= render 'form' %>

app/views/ingredients/show.html.erb
<div class="container">

  <%= render 'shared/page_title', title: "#{@ingredient.name}" %>
 
  <% if @ingredient.recipes.count != 0 %> 
    <h4 align="center">Recipes containing <%=  @ingredient.name %></h4>
    
    <div align="center">
       <%= will_paginate @ingredient_recipes %>
    </div>
    
    <%= render 'recipes/recipe', obj: @ingredient_recipes %>
    
    <div align="center">
      <%= will_paginate @ingredient_recipes %>
    </div>
  <% else %>
    <h4 align="center">No recipes yet!</h4>
  <% end %>
  
  <div class="col-md-offset-4 col-md-4 back-link"><%= link_to '[ cancel and go back to ingredients listing ]', ingredients_path %></div>